### ISSUE TITLE
Issue when loading Level.sav

### ISSUE THREAD

**Issue by imtheluk** [deafdudecomputers/PalWorldSaveTools#1]
Hi, I have a bit of a problem with the save tool.
When i launch it to convert my sav to json and get my player id to transfer it correctly, nothing happens.

I get this error, whatever i try to launch :
File "C:\Users\imthe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 493, in property
raise Exception(f"Unknown type: {type_name} ({path})")
Exception: Unknown type: ByteProperty (.SaveParameter.Level)

Do you have an idea about how to resolve this?
(I can't link the save zip because the file is too big, around 150mb)

**Comment by deafdudecomputers** [comment]
It should work, that error doesn't apply on my version of palworld_save_tools. Have you tried my version yet?

**Comment by imtheluk** [comment]
Actually, i'm not really good with python and coding, can you explain me how do I use your version please?

**Comment by deafdudecomputers** [comment]
Just download from the attachment I post on that [comment. ](https://github.com/cheahjs/palworld-save-tools/issues/187#issuecomment-2359196290)

And copy the whole folder after extracting, into where the tool you're trying to work with. It should have same folder name "palworld_save_tools".

**Comment by imtheluk** [comment]
Woah, I don't know if i'm tired or high but i tried this a few time before, i re-tried it after seeing ur message and it instantly worked..
Thanks!!

**Comment by TayVill01** [comment]
> Just download from the attachment I post on that [comment. ](https://github.com/cheahjs/palworld-save-tools/issues/187#issuecomment-2359196290)
> 
> And copy the whole folder after extracting, into where the tool you're trying to work with. It should have same folder name "palworld_save_tools".

so i copy the contents of the folder into the existing root of the palworld-save-tools-windows-v0.13.0? I tried and it didn't work. I still use the convert.cmd for the Level.sav?
