### ISSUE TITLE
Feature Request: Remove Specific Base

### ISSUE THREAD

**Issue by ArmGadge** [deafdudecomputers/PalWorldSaveTools#10]
Hello, this is a feature request, but can I remove any specific base?
My server enabled auto guild purging by using bAutoResetGuildNoOnlinePlayers from the middle, but seems not working correctly.
It seems not affect to bases which built before that variable is enabled.

Also my server have a rule of palbox placement, so I want to remove the base manually when I saw if someone violate it.

I have heard this can be done by using mod, but I'm using Linux, so I wish this feature is implemented on your tool.

**Comment by deafdudecomputers** [comment]
Unfortunately, I do not plan on this addition any time soon. But I'll consider it in future.

**Comment by deafdudecomputers** [comment]
Furthermore, make sure all players in that guild is offline at least of what you set to for automated base deletion to kick in. And make sure building deterioration is enabled for that to also kick in to help as well. 

Hopefully these tips helps. I'll consider about bases deletion in near future.
