### ISSUE TITLE
migrate 

### ISSUE THREAD

**Issue by rainteas** [deafdudecomputers/PalWorldSaveTools#11]
Do you have a server save migration script that can migrate individual player saves from the old server to the new server?

**Comment by rainteas** [comment]
I am Chinese, and my English is not very good.

**Comment by deafdudecomputers** [comment]
It should work regardless of what server it is. Unless you're trying to change from Xbox to Steam, which can't be done as far as I know. Correct me if I'm wrong here. You simply make a copy of "Saved" folder, and transfer it over to different server.

**Comment by rainteas** [comment]
I might have misunderstood earlier. Here's an example, please take a look at the following link:

https://github.com/jmkl009/PalworldCharacterTransfer

I only want to transfer a single character.

**Comment by rainteas** [comment]
> 不管是哪个服务器，它都应该可以工作。除非你试图从 Xbox 切换到 Steam，但据我所知这是不可能的。如果我错了，请纠正我。你只需复制“已保存”文件夹，然后将其传输到不同的服务器。


I might have misunderstood earlier. Here's an example, please take a look at the following link:
https://github.com/jmkl009/PalworldCharacterTransfer
I only want to transfer a single character.

**Comment by rainteas** [comment]
> It should work regardless of what server it is. Unless you're trying to change from Xbox to Steam, which can't be done as far as I know. Correct me if I'm wrong here. You simply make a copy of "Saved" folder, and transfer it over to different server.


I might have misunderstood earlier. Here's an example, please take a look at the following link:

https://github.com/jmkl009/PalworldCharacterTransfer

I only want to transfer a single character.

**Comment by deafdudecomputers** [comment]
Understood! Is that tool not working? I can probably add a fix for that tool, if you want?

**Comment by deafdudecomputers** [comment]
> > It should work regardless of what server it is. Unless you're trying to change from Xbox to Steam, which can't be done as far as I know. Correct me if I'm wrong here. You simply make a copy of "Saved" folder, and transfer it over to different server.
> 
> I might have misunderstood earlier. Here's an example, please take a look at the following link:
> 
> https://github.com/jmkl009/PalworldCharacterTransfer
> 
> I only want to transfer a single character.

https://github.com/deafdudecomputers/PalWorldSaveTools/releases

Try the character_transfer version I updated from original one you posted. Hopefully that works for you. I've tested it myself and it seems to be working.

**Comment by rainteas** [comment]
> > > It should work regardless of what server it is. Unless you're trying to change from Xbox to Steam, which can't be done as far as I know. Correct me if I'm wrong here. You simply make a copy of "Saved" folder, and transfer it over to different server.
> > 
> > 
> > I might have misunderstood earlier. Here's an example, please take a look at the following link:
> > https://github.com/jmkl009/PalworldCharacterTransfer
> > I only want to transfer a single character.
> 
> https://github.com/deafdudecomputers/PalWorldSaveTools/releases
> 
> Try the character_transfer version I updated from original one you posted. Hopefully that works for you. I've tested it myself and it seems to be working.

Thank you very much, this is very helpful to me. I will try to use it.
I tried to fix the example project I sent earlier, but there was an issue with the weapon durability. I'm not sure how to fix it, so I’m asking for your help.

**Comment by rainteas** [comment]
> > > It should work regardless of what server it is. Unless you're trying to change from Xbox to Steam, which can't be done as far as I know. Correct me if I'm wrong here. You simply make a copy of "Saved" folder, and transfer it over to different server.
> > 
> > 
> > I might have misunderstood earlier. Here's an example, please take a look at the following link:
> > https://github.com/jmkl009/PalworldCharacterTransfer
> > I only want to transfer a single character.
> 
> https://github.com/deafdudecomputers/PalWorldSaveTools/releases
> 
> Try the character_transfer version I updated from original one you posted. Hopefully that works for you. I've tested it myself and it seems to be working.

![QQ20240930-200135](https://github.com/user-attachments/assets/3544c328-837c-4e3e-8e69-91b02eef740a)

**Comment by deafdudecomputers** [comment]
[character_transfer.zip](https://github.com/user-attachments/files/17193012/character_transfer.zip)
Can you try this? I think there's tons more to your save than my test save, which is the reason it'll error out here and there.

**Comment by rainteas** [comment]
> [character_transfer.zip](https://github.com/user-attachments/files/17193012/character_transfer.zip) Can you try this? I think there's tons more to your save than my test save, which is the reason it'll error out here and there.

v0.8.8
![image](https://github.com/user-attachments/assets/0ac08a90-9db9-4180-83b3-674e611e3607)
![image](https://github.com/user-attachments/assets/a425fc80-5028-4a3e-855d-02922d2bfaee)


After the migration, all weapon and equipment durability values are lost.

**Comment by deafdudecomputers** [comment]
I'm guessing this only affects the ones on the person, not in the inventory of that person - correct? 

I'll take a look and attempt a fix on that.

**Comment by rainteas** [comment]
It will affect all items with durability, including those in the storage.

**Comment by rainteas** [comment]
> I'm guessing this only affects the ones on the person, not in the inventory of that person - correct?
> 
> I'll take a look and attempt a fix on that.
> 
> Upon creating new weapons, they seem to work. So, I think the transfer themselves breaks the durability and etc.

It will affect all items with durability, including those in the storage.

**Comment by deafdudecomputers** [comment]
I'm sorry, I can't reliably fix this. You'd need to wait for the original dev of this tool to update and fix. I tried my best to fix this, but I can't seem to pinpoint which part of the tool is causing this. My assumption on this is that it's one of the prefix which triggers this issue. And the recent update changed the save structure, which nullifies the prefix. This prefix needs to be updated from original dev. 

I apologize for the issue of weapon/armor/etc being useless due to this.

**Comment by deafdudecomputers** [comment]
> > [character_transfer.zip](https://github.com/user-attachments/files/17193012/character_transfer.zip) Can you try this? I think there's tons more to your save than my test save, which is the reason it'll error out here and there.
> 
> v0.8.8 ![image](https://github.com/user-attachments/assets/0ac08a90-9db9-4180-83b3-674e611e3607) ![image](https://github.com/user-attachments/assets/a425fc80-5028-4a3e-855d-02922d2bfaee)
> 
> After the migration, all weapon and equipment durability values are lost.

As of latest version, I've fixed both pals not transferrable and durability not transferrable. Both now works. Let me know if it works for you.

https://github.com/deafdudecomputers/PalWorldSaveTools/releases/latest
