### ISSUE TITLE
 LocalIdSearchPrefix

### ISSUE THREAD

**Issue by coni90** [deafdudecomputers/PalWorldSaveTools#13]
> Traceback (most recent call last):
>   File "C:\Users\Falcom\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
>     return self.func(*args)
>   File "C:\Users\Falcom\Desktop\PalworldSaveTools.v0.8.6\character_transfer\char-export.py", line 770, in main
>     target_guid = find_id_match_prefix(target_dynamic_container['ID']['value'],![Sin título](https://github.com/user-attachments/assets/0d028379-c055-4e80-b557-e0725da99024)

    
    
###    im so sorry, had the server tab open and ended submiting this in the whrong place, i deeply apologize.

**Comment by deafdudecomputers** [comment]
Can you retry the steps with v0.8.7 just in case?

I'll take a look into this soon.

**Comment by deafdudecomputers** [comment]
[PalworldSaveTools.v0.8.8.zip](https://github.com/user-attachments/files/17217139/PalworldSaveTools.v0.8.8.zip)


Kindly try this fix for me please.

**Comment by coni90** [comment]
> [PalworldSaveTools.v0.8.8.zip](https://github.com/user-attachments/files/17217139/PalworldSaveTools.v0.8.8.zip)
> 
> Kindly try this fix for me please.

success ... kinda.
no bases , i still have my items, but my weapons doesnt reload. no pals in party.

**Comment by deafdudecomputers** [comment]
It doesn't transfer bases/pals that are on bases. It does transfer your items/party pals/palbox pals. 

Doesn't reload? No pals in party? I'll need to take a look into these two.

**Comment by coni90** [comment]
> It doesn't transfer bases/pals that are on bases. It does transfer your items/party pals/palbox pals.
> 
> Doesn't reload? No pals in party? I'll need to take a look into these two.

i see, at least its a star, how should i transfer bases and pal and etc, i see there is a tutorial on steam saves, but no on gamepass version structure.

**Comment by deafdudecomputers** [comment]
That's typically for local host to dedicated server. But you can try if you want to. Both are "similar", but the platforms are different.

**Comment by deafdudecomputers** [comment]
Just tried it myself.

Party pals are intact in my party.

![image](https://github.com/user-attachments/assets/e99cb7e6-28a1-4914-aa36-bc201023f511)

I'll take a look at guns now.

**Comment by deafdudecomputers** [comment]
![image](https://github.com/user-attachments/assets/52cb3d17-0222-423d-b74c-c09e6344c3c4)
Seems to be fine to me here?

**Comment by coni90** [comment]
> ![image](https://private-user-images.githubusercontent.com/164821928/372671040-52cb3d17-0222-423d-b74c-c09e6344c3c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MjIzMDUsIm5iZiI6MTcyNzgyMjAwNSwicGF0aCI6Ii8xNjQ4MjE5MjgvMzcyNjcxMDQwLTUyY2IzZDE3LTAyMjItNDIzZC1iNzRjLWMwOWU2MzQ0YzNjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQyMjMzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDFkMDlmNjQyMjg5NzUzNmI5ZGQyYjczNTNiZjdhYzUyNWI0MDA2ZmIzOWQ1MGM0M2E0YjMyODQyZjNkZGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FpcAD8XdtnCHror4RcquH9YxIVQke3jJgYxs5xNpt-o) Seems to be fine to me here?
here i recorded said vehaviour: 
https://drive.google.com/file/d/1GfcrRWBNmO5wgXFipTXm2MACi5vnyEHZ/view?usp=sharing

here the original save that im using to transfer the characters from: 
https://drive.google.com/file/d/1seQ6fkCJudnq7TmWxv8lVzuZeHnxcvRb/view?usp=sharing

**Comment by deafdudecomputers** [comment]
That's apex game you're recording?

Also, the saves should be separate.

First save in first location should have Level.sav and Players folder

Second save in second location should have Level.sav and Players folder.

**Comment by coni90** [comment]
> That's apex game you're recording?
> 
> Also, the saves should be separate.
> 
> First save in first location should have Level.sav and Players folder
> 
> Second save in second location should have Level.sav and Players folder.
> 
> Then it might not work very well for gamepass version(xbox platform). Sorry for the inconvenience. :(

i dont understand what apex stand for haha . yes, i see that apparently has issues w the saves, but is there going to be any support for gamepass version in the future at least? it would be a shame that only could be for steam tbh. the tool looks very promising and usefull in so many aspects. :(

**Comment by deafdudecomputers** [comment]
> > That's apex game you're recording?
> > Also, the saves should be separate.
> > First save in first location should have Level.sav and Players folder
> > Second save in second location should have Level.sav and Players folder.
> > Then it might not work very well for gamepass version(xbox platform). Sorry for the inconvenience. :(
> 
> i dont understand what apex stand for haha . yes, i see that apparently has issues w the saves, but is there going to be any support for gamepass version in the future at least? it would be a shame that only could be for steam tbh. the tool looks very promising and usefull in so many aspects. :(

https://drive.google.com/file/d/1GfcrRWBNmO5wgXFipTXm2MACi5vnyEHZ/view

You posted this link. It takes me to apex game video?

**Comment by coni90** [comment]
> > > That's apex game you're recording?
> > > Also, the saves should be separate.
> > > First save in first location should have Level.sav and Players folder
> > > Second save in second location should have Level.sav and Players folder.
> > > Then it might not work very well for gamepass version(xbox platform). Sorry for the inconvenience. :(
> > 
> > 
> > i dont understand what apex stand for haha . yes, i see that apparently has issues w the saves, but is there going to be any support for gamepass version in the future at least? it would be a shame that only could be for steam tbh. the tool looks very promising and usefull in so many aspects. :(
> 
> https://drive.google.com/file/d/1GfcrRWBNmO5wgXFipTXm2MACi5vnyEHZ/view
> 
> You posted this link. It takes me to apex game video?

im so sorry , the drive was in list view so coudnt see the preview and sent whron gameplay haha my apologies
https://drive.google.com/file/d/1pbcEHWjVlmp__aTRXp_ZityXKwkvb5B3/view?usp=sharing

**Comment by deafdudecomputers** [comment]
No problem. Yeah, I see it. I think it may have to do with different structures on Xbox vs Steam.
