### ISSUE TITLE
I've got this problem when click on fix_host_save.cmd 

### ISSUE THREAD

**Issue by PCake0w0** [deafdudecomputers/PalWorldSaveTools#14]
Found Python at C:\Users\PCake\AppData\Local\Microsoft\WindowsApps\python.exe
Python Version: Python 3.11.9
Executing fix_host_save.py using C:\Users\PCake\AppData\Local\Microsoft\WindowsApps\python.exe...
Save Path: D:\Pal\PalworldSaveTools.v0.8.8\LocalWorldSave\Level.sav
Running: "C:\Users\PCake\AppData\Local\Microsoft\WindowsApps\python.exe" "fix_host_save.py"
Attempting to ensure pip is installed...
Pip installed successfully.
Attempting to find msgpack...
msgpack is already installed.
Attempting to find palworld_coord...
palworld_coord not found. Installing...
Failed to install palworld_coord. Error: Command '['C:\\Users\\PCake\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\python.exe', '-m', 'pip', 'install', 'palworld_coord', '--target=D:\\Pal\\PalworldSaveTools.v0.8.8\\external_libs', '--no-cache-dir']' returned non-zero exit status 1.
Attempting to find psutil...
psutil is already installed.
Attempting to find palworld_save_tools...
palworld_save_tools is already installed.
Attempting to find matplotlib...
matplotlib not found. Installing...
Failed to install matplotlib. Error: Command '['C:\\Users\\PCake\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\python.exe', '-m', 'pip', 'install', 'matplotlib', '--target=D:\\Pal\\PalworldSaveTools.v0.8.8\\external_libs', '--no-cache-dir']' returned non-zero exit status 1.
Attempting to find pandas...
pandas is already installed.
Attempting to find cityhash...
cityhash is already installed.
Traceback (most recent call last):
  File "D:\Pal\PalworldSaveTools.v0.8.8\fix_host_save.py", line 1, in <module>
    from fix_save import *
  File "D:\Pal\PalworldSaveTools.v0.8.8\fix_save.py", line 7, in <module>
    from internal_libs.import_libs import *
  File "D:\Pal\PalworldSaveTools.v0.8.8\internal_libs\import_libs.py", line 78, in <module>
    import psutil, msgpack, palworld_coord
ModuleNotFoundError: No module named 'palworld_coord'

**Comment by deafdudecomputers** [comment]
This likely occurs due to two reasons:

1) WindowsApp bases Python isn't reliable. Consider using the one from official Python via python.org/downloads

2)external drives, such as D\: may cause some conflicting installations.

**Comment by deafdudecomputers** [comment]
I still suggest using the official version of python, via python.org/downloads.

WindowsApps is the issue here. I am unable to help in this situtation. As I can see, some packages are able to be installed, but some of them aren't able to install. Again, I suggest you to use official version. Don't use WindowsApps version.

**Comment by PCake0w0** [comment]
Yep Ty for that

**Comment by PCake0w0** [comment]
Its working properly now Tys
