### ISSUE TITLE
Unable to get past cityhash

### ISSUE THREAD

**Issue by BiohazzardXIII** [deafdudecomputers/PalWorldSaveTools#17]
Hello, I have python installed from official python site and I have installed the c++ AIO and everytime i run the cmd it gets to installing cityhash and then fails stating no module found.

I tried installing cityhash manually with pip install cityhash 

And I get an error saying it needs c++ 14 + which should be installed from the AIO package. 

Any help would be greatfull

**Comment by BiohazzardXIII** [comment]
Here are some screenshots of the errors and my installed programs.
![Screenshot 2024-10-11 190437](https://github.com/user-attachments/assets/cad25a94-1e1c-41fa-8652-6648e44b8b27)
![Screenshot 2024-10-11 190615](https://github.com/user-attachments/assets/79ccd259-2365-4e7d-8f94-4b9783bb3280)
![Screenshot 2024-10-11 190645](https://github.com/user-attachments/assets/4a3bcdcf-d4af-4fa6-90c1-f4a74209d908)
![Screenshot 2024-10-11 190702](https://github.com/user-attachments/assets/432a1028-b8c1-482a-b874-a3f2d8e47696)
![Screenshot 2024-10-11 191332](https://github.com/user-attachments/assets/8cf36e66-043a-42e4-b07e-443d24d69221)

**Comment by BiohazzardXIII** [comment]
Good day, this can be closed. I fixed it. Not entirely sure what messed it up but a wipe of the VM and recreate and start from scratch worked. cityhash installed and tool is working. Thanks

**Comment by JackWilko23** [comment]
im currently having this problem but wiping the download and trying again did nothing so im really unsure where to go now
