### ISSUE TITLE
fix_host_save infinite yield

### ISSUE THREAD

**Issue by marinatedsushi** [deafdudecomputers/PalWorldSaveTools#22]
Tried running the cmd file and never get an output or input in terminal. 

Also tried directly running python, `python fix_host_save.py "C:\Users\16782\PalWorldSaveTools\LocalWorldSave" F79E68BA000000000000000000000000`

See no output in terminal. when the fix_save import is removed, it errors. Not a python expert, so im assuming one of the imports is yielding.

**Comment by marinatedsushi** [comment]
https://github.com/deafdudecomputers/PalWorldSaveTools/issues/21

**Comment by marinatedsushi** [comment]
![image](https://github.com/user-attachments/assets/3ce1e4ce-7731-4f46-8b45-3c8bf743a7ae)

**Comment by marinatedsushi** [comment]
followed instructions from other issue. got it running but after inputing the old and new guid, it asks for it again

**Comment by marinatedsushi** [comment]
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect
Warning: EOF not reached for EPalBaseCampModuleType::PassiveEffect

**Comment by deafdudecomputers** [comment]
Mind posting your save, please? Because I do NOT have this issue.

**Comment by marinatedsushi** [comment]
[LocalWorldSave.zip](https://github.com/user-attachments/files/18220728/LocalWorldSave.zip)

**Comment by deafdudecomputers** [comment]
> [LocalWorldSave.zip](https://github.com/user-attachments/files/18220728/LocalWorldSave.zip)

Which one are we trying to transfer? There are two different regular saves and one "host" save.

**Comment by marinatedsushi** [comment]
Trying to transfer the host save to F79E68BA000000000000000000000000

**Comment by deafdudecomputers** [comment]
[version.txt](https://github.com/user-attachments/files/18220735/version.txt)
Try this. It didn't error out for me.

![image](https://github.com/user-attachments/assets/894113d4-bb3e-4af7-96fb-e090f46cebef)

**Comment by marinatedsushi** [comment]
my vps is acting up, can't access the file manager. will test this asap. thanks!

**Comment by marinatedsushi** [comment]
![image](https://github.com/user-attachments/assets/ac047353-52fc-40c0-89bb-923ee174d751)

One odd thing, looks like i don't have any of my teleport points unlocked or access to my base

**Comment by deafdudecomputers** [comment]
Are you 100% sure that F79E68BA000000000000000000000000 is your save? Also, is the owner of bases actually you? Or someone else?

**Comment by marinatedsushi** [comment]
so 12D86A6A000000000000000000000000 is me, the other save is the host of the coop world. When the old coop host tries to join, they get this error: failedinvalidloginplayercharacterhandle

**Comment by marinatedsushi** [comment]
Both saves have a few bases, i'm able to join, all my pals and chests are there but i can't spawn at my base or use any teleport points

**Comment by deafdudecomputers** [comment]
![image](https://github.com/user-attachments/assets/7496113a-e296-4ed4-a687-3cb1061dfba9)
I was able to see your bases on map. And I'm using that save as my own on my server works fine here.

![image](https://github.com/user-attachments/assets/11ace962-6786-48c5-91a9-da5f37b38e86)

![image](https://github.com/user-attachments/assets/bee9a288-6d3e-4438-a478-1366b89e27ab)

**Comment by deafdudecomputers** [comment]
Did they delete all saves and copy from updated LocalWorldSave? Level.sav and Players folder?
That has to be done.

**Comment by marinatedsushi** [comment]
I am the one setting up the new dedicated server. Do I delete all save data and the "new" save should only have Level.sav and Players foldder

**Comment by deafdudecomputers** [comment]
This is server; delete all files folders in this location(server id/name of the folder may differ).

![image](https://github.com/user-attachments/assets/91bf1ee9-ff85-4eb2-bf01-527431f20958)

Then you want to copy everything from inside of LocalWorldSave, then paste it into server id/name folder.

**Comment by marinatedsushi** [comment]
I had to switch dedicated server host to new vps provider this morning. Do I have to go through the steps again from step 1 for it to function properly?
