### ISSUE TITLE
v0.4.11 broke the tools

### ISSUE THREAD

**Issue by lethe4846** [deafdudecomputers/PalWorldSaveTools#23]
A lot of errors.  Just a whole bunch you know.

**Comment by deafdudecomputers** [comment]
[https://github.com/cheahjs/palworld-save-tools/issues/192]#192(url) Already mentioned it. Appreciate it tho. :)

**Comment by deafdudecomputers** [comment]
https://github.com/deafdudecomputers/PalWorldSaveTools/releases/ 

v0.9.3 of PalWorldSaveTools has been released.
