### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by CarpeDiemYY** [deafdudecomputers/PalWorldSaveTools#24]
Our server is setted up yesterday, and I found the same question about 
https://github.com/cheahjs/palworld-save-tools/issues/192

I just know a little in code, and I am a little confused about `Readme.md` and `fix_host_save_readme.txt`

Here is my world, the host is 00000000000000000000000000000001 and the character that got created is AF03BD28000000000000000000000000. And the host is the leader of guild.

I would really appreciate it if you could help me
Thank you!

Since the file is too big, you can find it here 
https://github.com/CarpeDiemYY/Palworld_file/releases/

**Comment by CarpeDiemYY** [comment]
Sorry about the link

**Comment by deafdudecomputers** [comment]
[DE4CB2C443FEF36161354ABE5C41820B_Updated.zip](https://github.com/user-attachments/files/18237582/DE4CB2C443FEF36161354ABE5C41820B_Updated.zip)
Sorry for the delay, was busy.

**Comment by CarpeDiemYY** [comment]
Thanks a million！
