### ISSUE TITLE
Help with files

### ISSUE THREAD

**Issue by pedrovr1** [deafdudecomputers/PalWorldSaveTools#25]
Hi I've been trying to set up a world in the past days but I just can't make it work.

The host is 00000000000000000000000000000001 new character created is 02E73813000000000000000000000000

Could you help me out ? https://github.com/pedrovr1/palworld-help

Thanks

**Comment by deafdudecomputers** [comment]
I can't do this without actual 02E73813000000000000000000000000.sav file.

You need to make it so that zipped folder has 

*Players folder
    *00000000000000000000000000000001.sav
    *02E73813000000000000000000000000.sav
*Level.sav

Thank you.

**Comment by pedrovr1** [comment]
Hi I added the file to the repository thank you for answering

**Comment by deafdudecomputers** [comment]
[9676B5D249D13089C6EB14A889554D01_Updated.zip](https://github.com/user-attachments/files/18247078/9676B5D249D13089C6EB14A889554D01_Updated.zip)
