### ISSUE TITLE
How do I get the list of player names and matching SAV filenames? It's not clear.

### ISSUE THREAD

**Issue by StrikerMan780** [deafdudecomputers/PalWorldSaveTools#27]
Title. Just trying to get a list of all the IDs with names on my server so I can convert them to the new IDs for dedicated.

**Comment by deafdudecomputers** [comment]
When you run the fix_save.cmd, it'll show you the players and their UIDs.
It's easier once you run the tool, and it'll has players.log. That information has names and their uids, which you can use to find saves of each player.
![image](https://github.com/user-attachments/assets/8b06f819-e02f-49b4-95d6-732b95a9297b)

Good luck! :)
