### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by luisflorido** [deafdudecomputers/PalWorldSaveTools#3]
I used the `fix_host_save` and worked, but when I open the server after some seconds (around 30s) the server just crashes without any info, can you help on that?

**Comment by deafdudecomputers** [comment]
How are you hosting the server? I need details. Did you ever host the server before? There should be crashes folder and dumps.

**Comment by luisflorido** [comment]
I'm hosting on windows, when I try to host in a generated world works perfect, but when I convert my world using your tool like I said the server crashes, about the dumps, what can I provide to help? I looked at crashes but the most of exceptions are from unhandled exception
`Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000` (CrashContext.runtime-xml file in Saved->Crashes)

**Comment by deafdudecomputers** [comment]
Can you retry the steps found in fix_host_save_readme.txt(with screenshots included, for clear instructions), and post back if it still crashes?
