### ISSUE TITLE
Attempting fix_host_save Fails

### ISSUE THREAD

**Issue by Uplinkpro** [deafdudecomputers/PalWorldSaveTools#30]
Attempting to get fix_host_save to work it finishes the process successfully but in game it give me this error:
![image](https://github.com/user-attachments/assets/f60e0626-1f77-4356-b2a8-281f82a3b077)
not sure where to go from here thanks

**Comment by deafdudecomputers** [comment]
Redo steps again. Make sure to follow them step by step. There's a step you've missed. That error happened because you didn't do the steps properly.

**Comment by Uplinkpro** [comment]
Thanks i redid it and it seems to work but now my firends are getting that same error do i need to do something with there saves??
