### ISSUE TITLE
Fix host save failing initial load

### ISSUE THREAD

**Issue by jtrain256** [deafdudecomputers/PalWorldSaveTools#31]
Assets are failing to load when VS file note found and "PySimpleGUI" not found

![image](https://github.com/user-attachments/assets/720bf142-17df-4476-bda4-86ed4464e0fe)

**Comment by Djeloan** [comment]
yeah, same here...

**Comment by deafdudecomputers** [comment]
Have you followed the installation notes? Are you using official Python? 3.13 as latest?  Did you enable venv? Did you install via requirements.txt, in case you don't use my .cmd files which automates them?

**Comment by deafdudecomputers** [comment]
I just removed VS tools completely and I'm now getting this error.

![image](https://github.com/user-attachments/assets/d14f7c48-0a95-40c8-b9c5-92538cc09dad)

It clearly says this: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

![image](https://github.com/user-attachments/assets/68adca1c-75f3-4f77-bf5b-4f5c7c9a134d)

Make sure to tick the option that says Desktop development with C++, then press install.

After it's done installing, start up the tool again. It should work now.

![image](https://github.com/user-attachments/assets/be2627d4-4481-4f39-aef5-6d9eb59c900d)

Good luck. Hope this instructions are helpful.

**Comment by Djeloan** [comment]
Installed everything as in the notes
![Screenshot_1](https://github.com/user-attachments/assets/ab1182bc-8cfe-44dd-bc43-b9ee35f8d7c6)
![Screenshot_2](https://github.com/user-attachments/assets/933947a3-18ce-4f27-99f4-2c24e3612c82)

**Comment by deafdudecomputers** [comment]
Again, DID you tick the option that says: Desktop development with C++. That's the only reason it's failing, is because you didn't tick that option.

**Comment by Djeloan** [comment]
You're right, i did not select that option during the installation... Installing it now and will try in a few minutes, will let you know if it works.

Is it possible to write that on the readme.md, as it's not really clear which options need to be selected during the installation process

**Comment by deafdudecomputers** [comment]
Yes, I will include that in readme.md.

**Comment by Djeloan** [comment]
Yup - that was it. 
It works now, thank you very much for your help and your time.

Hopefully it works for you too @jtrain256

**Comment by deafdudecomputers** [comment]
Glad to help out. I've already updated the readme.md. Thanks for troubleshooting with me.

**Comment by jtrain256** [comment]
Thank you!

**Comment by jtrain256** [comment]
Unfortunately cityhash fails to load with all the other requirements installed. I tried this across two computers.
![image](https://github.com/user-attachments/assets/64c4b16d-d7cc-4480-a25d-09ae894b112d)

**Comment by josubum** [comment]
![Image](https://github.com/user-attachments/assets/904acd7e-2f85-470c-892c-57d60572f14c)

![Image](https://github.com/user-attachments/assets/c6081ad0-ae38-476b-94fe-d8d293dc38ed)

![Image](https://github.com/user-attachments/assets/eb1ab2a1-a876-45d5-ba58-1280efa55617)

I checked and ran everything as you said and still get a cityhash error. It's really sad, is there any way to fix it?
