### ISSUE TITLE
fix_save says it cant find python

### ISSUE THREAD

**Issue by stormlust** [deafdudecomputers/PalWorldSaveTools#34]
so i basically have no clue what im doing or how to work/use python or any of this but i was fallowing the readme for the fixed save and when i opened  file i get the fallowing
![palworld issues](https://github.com/user-attachments/assets/524da1d6-4797-4a0a-9b18-a9f7dcf51229)
yeti have python 3.13 installed so im at a loss i even tried clicking on the python file its self and it just open and closes. so i have no clue if im doing something wrong, i did try looking for videos on youtube to see if anyone had a guide up on how to use this to see if that would make it easier on for me to fallow along but couldnt find any. really need the help so i can get my offline world working right for me showing up on my dedicated sever

**Comment by deafdudecomputers** [comment]
# How to Install Python Properly (Without Breaking Things!)

## 1. Download Python
- Go to the official site: [https://www.python.org/downloads/](https://www.python.org/downloads/).
- Download the version for your operating system.

## 2. Run the Installer
- Open the downloaded installer (probably named something like `python-<version>.exe`).

## 3. **The Important Part**
- Before clicking **Install Now**, **CHECK** the box at the bottom that says:  
  **"Add Python to PATH"** 🟩  
  (*This is what makes Python accessible from the command line!*)

![Add Python to PATH checkbox](https://i.imgur.com/atUrP5j.png) 

## 4. Install Python
- Click **Install Now** and let it do its magic.

## 5. Verify the Installation
- Open a terminal (Command Prompt, PowerShell, or Bash).
- Type:
  ```bash
  python --version

**Comment by MMMDURADIS** [comment]
If you haven't solved it, follow the top two answers on this : https://stackoverflow.com/questions/65348890/python-was-not-found-run-without-arguments-to-install-from-the-microsoft-store
it worked for me
