### ISSUE TITLE
Convert does not work

### ISSUE THREAD

**Issue by KyubeGG** [deafdudecomputers/PalWorldSaveTools#35]
First of all, I have absolutely no knowledge of programming etc. so I have no idea what the error may be here:

```python
Converting Level.sav to JSON, saving to Level.sav.json
Decompressing sav file
Traceback (most recent call last):
  File "E:\SYSTEM\Desktop\Neuer Ordner\PalWorldSaveTools.v1.0.0\convert.py", line 136, in <module>
    main()
    ~~~~^^
  File "E:\SYSTEM\Desktop\Neuer Ordner\PalWorldSaveTools.v1.0.0\convert.py", line 56, in main
    convert_sav_to_json(
    ~~~~~~~~~~~~~~~~~~~^
        args.filename,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        custom_properties_keys=args.custom_properties,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\SYSTEM\Desktop\Neuer Ordner\PalWorldSaveTools.v1.0.0\convert.py", line 87, in convert_sav_to_json
    raw_gvas, _ = decompress_sav_to_gvas(data)
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "E:\SYSTEM\Desktop\Neuer Ordner\PalWorldSaveTools.v1.0.0\external_libs\palworld_save_tools\palsav.py", line 26, in decompress_sav_to_gvas
    raise Exception(
        f"Not a compressed Palworld save, found {magic_bytes!r} instead of {MAGIC_BYTES!r}"
    )
Exception: Not a compressed Palworld save, found b'CNK' instead of b'PlZ'

``` 
this happens when I try to convert my GamePass save into a Json.

**Comment by deafdudecomputers** [comment]
That's because you didn't follow the notes or follow the readme...

If you are trying to use GamePass saves(Xbox Platform), make sure to use XPG save extractor then convert it to json. Then reconvert json back to Level.sav. Then use the tool.

**Comment by KyubeGG** [comment]
sorry, maybe i should have added it, but i used the xgp-save-extractor and got a .zip file (which i extracted) with the files for the game, from which i also got the sav file and the rest i have already explained.

i can't convert the json file back if i can't convert the save file into a json file.

**Comment by deafdudecomputers** [comment]
Post your save here, then.

**Comment by MMMDURADIS** [comment]
I have encountered the same bug, and just like @KyubeGG I am following the steps in the readme file, you can try with my save if you want :
[palworld_2535442590947126_2024-12-31_12_50_53.zip](https://github.com/user-attachments/files/18283047/palworld_2535442590947126_2024-12-31_12_50_53.zip)

**Comment by KyubeGG** [comment]
> Post your save here, then. Preferable in original state, the one you grab directly from gamepass. Not already converted, so that I can do it myself.

Thanks, here is the file extracted directly from xqp-save-extractor.

https://drive.google.com/drive/folders/1jxn3Sd-jrsQMMSNECA1DV9N-MiVlxbpD?usp=drive_link

(The zip file was too big, so I uploaded it via google drive)

**Comment by deafdudecomputers** [comment]
Thank you for that. I was able to debug and figure out why it's failing. I'm updating it atm.

**Comment by deafdudecomputers** [comment]
@KyubeGG 

Kindly go on https://github.com/deafdudecomputers/PalWorldSaveTools/releases and download again. Let me know if it works for you now.

**Comment by KyubeGG** [comment]
@deafdudecomputers It worked perfectly thanks for that. and depending on your time zone I wish you a happy new year.

**Comment by deafdudecomputers** [comment]
@KyubeGG Thank you for confirming and I wish you a happy new year as well! :)
