### ISSUE TITLE
Permission Errors on changing process priority

### ISSUE THREAD

**Issue by lethe4846** [deafdudecomputers/PalWorldSaveTools#5]
![image](https://github.com/user-attachments/assets/c21e1cf1-f8a3-49e0-84c8-50b2af28e256)

When running fix_save.py on OSX 15.0 , execution will fail due to permissions from trying to change process niceness.

**Comment by deafdudecomputers** [comment]
Updated and fixed on v0.7.6b.

**Comment by lethe4846** [comment]
Perfect!
