### ISSUE TITLE
convert.py throws structure byte error when converting sav file.

### ISSUE THREAD

**Issue by MuchDevSuchCode** [deafdudecomputers/PalWorldSaveTools#7]
When converting a save file from sav to json an unpack error occurs: 

  File "/home/agent/code/PalWorldSaveTools/palworld_save_tools/rawdata/item_container_slots.py", line 13, in decode
    value["value"] = decode_bytes(reader, data_bytes)
  File "/home/agent/code/PalWorldSaveTools/palworld_save_tools/rawdata/item_container_slots.py", line 29, in decode_bytes
    "corruption_progress_value": reader.float(),
  File "/home/agent/code/PalWorldSaveTools/palworld_save_tools/archive.py", line 334, in float
    val = FArchiveReader.unpack_float(self.data.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

**Comment by deafdudecomputers** [comment]
Mind sending me your Level.sav? I can take a look into this.

**Comment by deafdudecomputers** [comment]
Might I suggest v0.7.8 update I just released? https://github.com/deafdudecomputers/PalWorldSaveTools/releases Might fix that bug.

**Comment by deafdudecomputers** [comment]
The only thing that comes to my mind that -MAY- cause that error, is using Level.sav that isn't updated on/after v0.3.7 patch. Recent updates has fixed that issue. Can you please [download the latest release](https://github.com/deafdudecomputers/PalWorldSaveTools/releases) and reply back?
