### ISSUE TITLE
Possible to convert a server save back to a co-op one?

### ISSUE THREAD

**Issue by Contralitary** [deafdudecomputers/PalWorldSaveTools#8]
Hi, 

I greatly appreciate your work, especially given that you seem to be the only one keeping your tools up to date. 

I tried to convert my server save back to a co-op one using `fix_host_save.cmd`.  Since your script is similar to the obsolete one by xNul, I followed the procedures in that repo but the game kept crashing when loading the world after conversion. 

Was I doing something incorrectly or it is just not possible anymore? FYI here is my procedures in detail:
1. Created a co-op world in the game, picked up something for auto-save
2. Copied and pasted the player save `00000000000000000000000000000001.sav` of the new co-op world into the `Players` folder of the server save
3. Copied and pasted the `Players` folder and `Level.sav` of the server save into `LocalWorldSave`
4. Ran `fix_host_save.cmd`, set `00000000000000000000000000000001` as the new GUID and `%my previous GUID in the server save%` as the old one
5. The script worked fine
6. Copied and pasted the `Players` folder and `Level.sav` back to the folder of the new co-op world
7. Started the game and the world
8. The game crashed when the loading was almost finished because I could already hear the game sound. A UE access violation error popped up. 

Could you help me with this? Thanks in advance!

**Comment by deafdudecomputers** [comment]
I've honestly never tried transferring from server to local before. I'll take a look into this matter soon. I didn't realize it would work that way as well.

**Comment by deafdudecomputers** [comment]
Just followed your directions, it's just "backwards". I'm able to load in, but I don't retain my character from dedicated server to local save. :( Trying to figure out as to why.

**Comment by deafdudecomputers** [comment]
Scratch that, I'm able to make it work. It seems that I had to "re-copy" the 0001.sav from LocalWorldSave for second time, and it successfully loaded my character in.

**Comment by deafdudecomputers** [comment]
Can you redo the steps, and reply back if it works or not with my [latest release](https://github.com/deafdudecomputers/PalWorldSaveTools/releases)?

**Comment by Contralitary** [comment]
> Can you redo the steps, and reply back if it works or not with my [latest release](https://github.com/deafdudecomputers/PalWorldSaveTools/releases)?

Thanks for looking into the problems real fast! I was just about to mention the guild issue before I saw you were working on it already. 

Unfortunately, it doesn't seem to be getting resolved on my end. I used your latest v0.7.9 release and redid the whole thing but still lost my guild and bases. 

Forget about the UE crash: I was too dumb to recall that some mods have become unavailable with game updates, and they are exactly why. I got into the world as soon as I removed them. Sorry for the confusion.

**Comment by deafdudecomputers** [comment]
> > Can you redo the steps, and reply back if it works or not with my [latest release](https://github.com/deafdudecomputers/PalWorldSaveTools/releases)?
> 
> Thanks for looking into the problems real fast! I was just about to mention the guild issue before I saw you were working on it already.
> 
> Unfortunately, it doesn't seem to be getting resolved on my end. I used your latest v0.7.9 release and redid the whole thing but still lost my guild and bases.
> 
> Forget about the UE crash: I was too dumb to recall that some mods have become unavailable with game updates, and they are exactly why. I got into the world as soon as I removed them. Sorry for the confusion.

Did you remake new world, and did the rest? 

Sometimes that "new world" can be corrupted, and have to remake in some cases. Just in case if you didn't do that.

And glad it wasn't the tool that was causing the crashes. Thanks for letting me know about that.

**Comment by Contralitary** [comment]
> > > Can you redo the steps, and reply back if it works or not with my [latest release](https://github.com/deafdudecomputers/PalWorldSaveTools/releases)?
> > 
> > 
> > Thanks for looking into the problems real fast! I was just about to mention the guild issue before I saw you were working on it already.
> > Unfortunately, it doesn't seem to be getting resolved on my end. I used your latest v0.7.9 release and redid the whole thing but still lost my guild and bases.
> > Forget about the UE crash: I was too dumb to recall that some mods have become unavailable with game updates, and they are exactly why. I got into the world as soon as I removed them. Sorry for the confusion.
> 
> Did you remake new world, and did the rest?
> 
> Sometimes that "new world" can be corrupted, and have to remake in some cases. Just in case if you didn't do that.
> 
> And glad it wasn't the tool that was causing the crashes. Thanks for letting me know about that.

I redid from the very first step: create a co-op local world, if that's what you mean.

**Comment by deafdudecomputers** [comment]
Hmmm, should've of worked since it works for me. 

Did you miss a step or something? Or did my tool NOT update properly?

**Comment by Contralitary** [comment]
> Hmmm, should've of worked since it works for me.
> 
> Did you miss a step or something? Or did my tool NOT update properly?

Steps: I redid everything in the exact same way. I could make anyone in the guild as host for the newly converted world and enter the game with everything fine but the guild&base membership.

Tools: I updated the tools by completely delete the previous version before extracting the new ones. Then when the files were ready I ran `fix_host_save.cmd` and the download started, etc.

It was strange to me as well to see you could do that while I couldn't. Perhaps it could be the reason that the server save I'm using was originally converted from a co-op one? Maybe I should create a brand new save on my server and convert it to local save as an experiment.

**Comment by deafdudecomputers** [comment]
> It was strange to me as well to see you could do that while I couldn't. Perhaps it could be the reason that the server save I'm using was originally converted from a co-op one? Maybe I should create a brand new save on my server and convert it to local save as an experiment.

It's likely the "original" convert from co op to dedicated server may have of "corrupted" / "messed up" the save in a way that it can't be converted back into single/co op save again? Not sure if that's actually the case here, tho.

**Comment by Contralitary** [comment]
> > It was strange to me as well to see you could do that while I couldn't. Perhaps it could be the reason that the server save I'm using was originally converted from a co-op one? Maybe I should create a brand new save on my server and convert it to local save as an experiment.
> 
> It's likely the "original" convert from co op to dedicated server may have of "corrupted" / "messed up" the save in a way that it can't be converted back into single/co op save again? Not sure if that's actually the case here, tho.

I'll keep you updated once I finish the experiment. Probably it is the reason but I don't get it. Did you write the whole `fix_host_save.py` script on your own? I didn't look at the code but yours is very similar to [the one](https://github.com/xNul/palworld-host-save-fix?tab=readme-ov-file#guild-bug) I used before, even the warning message and the "have fun" message are the same. I had to apply the workaround for the guild bug there when I originally converted the save.

**Comment by deafdudecomputers** [comment]
> I'll keep you updated once I finish the experiment. Probably it is the reason but I don't get it. Did you write the whole `fix_host_save.py` script on your own? I didn't look at the code but yours is very similar to [the one](https://github.com/xNul/palworld-host-save-fix?tab=readme-ov-file#guild-bug) I used before, even the warning message and the "have fun" message are the same. I had to apply the workaround for the guild bug there when I originally converted the save.

Yes, it's using xNul's tool as he isn't available to update it as of lately. Also, I believe you MAY have of applied that transfer BEFORE he was able to see the issues around guild/bases and fix the issues then released it? Not sure, tho.

**Comment by Contralitary** [comment]
> > I'll keep you updated once I finish the experiment. Probably it is the reason but I don't get it. Did you write the whole `fix_host_save.py` script on your own? I didn't look at the code but yours is very similar to [the one](https://github.com/xNul/palworld-host-save-fix?tab=readme-ov-file#guild-bug) I used before, even the warning message and the "have fun" message are the same. I had to apply the workaround for the guild bug there when I originally converted the save.
> 
> Yes, it's using xNul's tool as he isn't available to update it as of lately. Also, I believe you MAY have of applied that transfer BEFORE he was able to see the issues around guild/bases and fix the issues then released it? Not sure, tho.

Tested. Successfully converted a new server save to a co-op one with the guild and bases intact, so it was my save that had some unknown problems, just like what you said. I guess I'll have to do that workaround again for this save, thank you so much for your help!

**Comment by deafdudecomputers** [comment]
> > > I'll keep you updated once I finish the experiment. Probably it is the reason but I don't get it. Did you write the whole `fix_host_save.py` script on your own? I didn't look at the code but yours is very similar to [the one](https://github.com/xNul/palworld-host-save-fix?tab=readme-ov-file#guild-bug) I used before, even the warning message and the "have fun" message are the same. I had to apply the workaround for the guild bug there when I originally converted the save.
> > 
> > 
> > Yes, it's using xNul's tool as he isn't available to update it as of lately. Also, I believe you MAY have of applied that transfer BEFORE he was able to see the issues around guild/bases and fix the issues then released it? Not sure, tho.
> 
> Tested. Successfully converted a new server save to a co-op one with the guild and bases intact, so it was my save that had some unknown problems, just like what you said. I guess I'll have to do that workaround again for this save, thank you so much for your help!

Thanks for the update. I'm sorry about your save being a bit messed up. Appreciate your updates.
