### ISSUE TITLE
fix_host_save.cmd stuck on download and extracting assets

### ISSUE THREAD

**Issue by hvlenxx** [deafdudecomputers/PalWorldSaveTools#9]
Not too sure why this is happening, any help would be great!

**Comment by deafdudecomputers** [comment]
Is everything working again? Let me know what you did to fix it. Would help others. Thank you.

**Comment by hvlenxx** [comment]
Yes, everything is working and I was able to transfer my save to a dedicated server with everything intact including the guild.
My issue was solved by simply reinstalling Visual Studios build tools again and running the cleanup.cmd

Thank you so much for this tool! In my search this seems to be the only one working at the moment
